import createClient from 'openapi-fetch'
import { type paths } from '../types/schema.d' // Auto-generated by openapi-typescript
import { getToken, clearToken, AUTH_LOGOUT_EVENT } from './token'

// The backend stamps every response with a per-request id (and logs the same
// value), exposed to the browser via CORS. Surfacing it on failures lets a user
// hand support an exact code that pinpoints the failing log line.
export const REQUEST_ID_HEADER = 'X-Request-Id'

/** Reads the backend request id from a response, if present. */
export function getRequestId(
  response: Response | undefined,
): string | undefined {
  return response?.headers.get(REQUEST_ID_HEADER) ?? undefined
}

/**
 * An error from a failed backend request that carries the request id, so the
 * UI catching it can show the user a support code. Thrown by data loaders (e.g.
 * {@link fetchLogsForDate}) that signal failure by throwing rather than returning.
 */
export class RequestError extends Error {
  readonly requestId?: string

  constructor(message: string, requestId?: string) {
    super(message)
    this.name = 'RequestError'
    this.requestId = requestId
  }
}

// The API base URL is injected at build time via VITE_API_BASE_URL. Production
// builds (Cloudflare Pages) set it to the backend's Cloudflare hostname; local
// dev falls back to the Go Chi server on localhost.
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8001'

export const apiClient = createClient<paths>({
  baseUrl,
})

// Attach the session token (when present) as a bearer header on every request,
// so protected endpoints (/v1/sync, /v1/logs, /v1/auth/me) authenticate transparently and
// anonymous clients simply send no header.
apiClient.use({
  onRequest({ request }) {
    const token = getToken()
    if (token) {
      request.headers.set('Authorization', `Bearer ${token}`)
    }
    return request
  },
  onResponse({ request, response }) {
    // A 401 on a request we authenticated means the token is expired or revoked:
    // clear it and signal the auth context to drop to a logged-out state. We only
    // react when a token was actually sent, so a 401 from /auth/verify (a wrong
    // code, no token attached) does not trigger a spurious logout.
    if (response.status === 401 && request.headers.has('Authorization')) {
      clearToken()
      window.dispatchEvent(new Event(AUTH_LOGOUT_EVENT))
    }
    return response
  },
})
