import createClient from 'openapi-fetch'
import { type paths } from '../types/schema.d' // Auto-generated by openapi-typescript

// The API base URL is injected at build time via VITE_API_BASE_URL. Production
// builds (Cloudflare Pages) set it to the backend's Cloudflare hostname; local
// dev falls back to the Go Chi server on localhost.
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8080'

export const apiClient = createClient<paths>({
  baseUrl,
})
