import createClient from 'openapi-fetch'
import { type paths } from '../types/schema.d' // Auto-generated by openapi-typescript
import { getToken, clearToken, AUTH_LOGOUT_EVENT } from './token'

// The API base URL is injected at build time via VITE_API_BASE_URL. Production
// builds (Cloudflare Pages) set it to the backend's Cloudflare hostname; local
// dev falls back to the Go Chi server on localhost.
const baseUrl = import.meta.env.VITE_API_BASE_URL ?? 'http://localhost:8080'

export const apiClient = createClient<paths>({
  baseUrl,
})

// Attach the session token (when present) as a bearer header on every request,
// so protected endpoints (/sync, /logs, /auth/me) authenticate transparently and
// anonymous clients simply send no header.
apiClient.use({
  onRequest({ request }) {
    const token = getToken()
    if (token) {
      request.headers.set('Authorization', `Bearer ${token}`)
    }
    return request
  },
  onResponse({ request, response }) {
    // A 401 on a request we authenticated means the token is expired or revoked:
    // clear it and signal the auth context to drop to a logged-out state. We only
    // react when a token was actually sent, so a 401 from /auth/verify (a wrong
    // code, no token attached) does not trigger a spurious logout.
    if (response.status === 401 && request.headers.has('Authorization')) {
      clearToken()
      window.dispatchEvent(new Event(AUTH_LOGOUT_EVENT))
    }
    return response
  },
})
