/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/logs': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Fetch water logs for a specific day
     * @description Returns the non-deleted water logs whose logged_at falls within the half-open range [from, to). The client passes the start of the selected local day and the start of the following day so day boundaries honour the client's timezone. Used to view historical days that are no longer cached locally.
     */
    get: {
      parameters: {
        query: {
          /** @description ISO-8601 timestamp marking the inclusive start of the range */
          from: string
          /** @description ISO-8601 timestamp marking the exclusive end of the range */
          to: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Logs within the requested range, most recent first */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['api.LogsResponse']
          }
        }
        /** @description Missing or invalid range parameters */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              [key: string]: string
            }
          }
        }
        /** @description Internal server or database error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              [key: string]: string
            }
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/sync': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Sync local water logs with the server
     * @description Pushes local changes (upserts) to the server and pulls remote changes (delta) made on other devices.
     */
    post: {
      parameters: {
        query?: {
          /** @description ISO-8601 Timestamp of the client's last sync */
          since?: string
        }
        header?: never
        path?: never
        cookie?: never
      }
      /** @description Array of local water logs to sync */
      requestBody: {
        content: {
          'application/json': components['schemas']['api.WaterLog'][]
        }
      }
      responses: {
        /** @description Successful sync response containing delta changes */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': components['schemas']['api.SyncResponse']
          }
        }
        /** @description Invalid request body */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              [key: string]: string
            }
          }
        }
        /** @description Internal server or database error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': {
              [key: string]: string
            }
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    'api.LogsResponse': {
      logs: components['schemas']['api.WaterLog'][]
    }
    'api.SyncResponse': {
      changes: components['schemas']['api.WaterLog'][]
      server_time: string
    }
    'api.WaterLog': {
      amount_ml: number
      id: string
      is_deleted: boolean
      logged_at: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
