/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Sync local water logs with the server
         * @description Push new local logs to the server and pull changes made on other devices.
         */
        post: {
            parameters: {
                query?: {
                    /** @description The server_updated_at timestamp from the client's last successful sync. */
                    since?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["WaterLog"][];
                };
            };
            responses: {
                /** @description Successfully processed sync data */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * Format: date-time
                             * @description Current server time to use for the next sync query.
                             */
                            server_time?: string;
                            changes?: components["schemas"]["ServerWaterLog"][];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A single record of water consumed generated by a client. */
        WaterLog: {
            /**
             * Format: uuid
             * @description Unique ID generated by the local device (Web/Desktop/Mobile).
             */
            id: string;
            /** @description Amount of water consumed in milliliters. */
            amount_ml: number;
            /**
             * Format: date-time
             * @description When the user drank the water (ISO 8601).
             */
            logged_at: string;
            /** @description Used for local-first sync. If true, the server tells other devices to delete this log. */
            is_deleted: boolean;
        };
        ServerWaterLog: components["schemas"]["WaterLog"] & {
            /** Format: date-time */
            server_updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
