// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type UserSetting struct {
	UserID          uuid.UUID
	Settings        []byte
	ServerUpdatedAt pgtype.Timestamptz
}

type WaterLog struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AmountMl        int32
	LoggedAt        pgtype.Timestamptz
	IsDeleted       bool
	ServerUpdatedAt pgtype.Timestamptz
}
