// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserSettings = `-- name: GetUserSettings :one
SELECT settings, server_updated_at FROM user_settings WHERE user_id = $1
`

type GetUserSettingsRow struct {
	Settings        []byte
	ServerUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetUserSettings(ctx context.Context, userID uuid.UUID) (GetUserSettingsRow, error) {
	row := q.db.QueryRow(ctx, getUserSettings, userID)
	var i GetUserSettingsRow
	err := row.Scan(&i.Settings, &i.ServerUpdatedAt)
	return i, err
}

const upsertUserSettings = `-- name: UpsertUserSettings :exec
INSERT INTO user_settings (user_id, settings, server_updated_at)
VALUES ($1, $2, $3)
ON CONFLICT (user_id) DO UPDATE SET
    settings          = EXCLUDED.settings,
    server_updated_at = EXCLUDED.server_updated_at
`

type UpsertUserSettingsParams struct {
	UserID          uuid.UUID
	Settings        []byte
	ServerUpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertUserSettings(ctx context.Context, arg UpsertUserSettingsParams) error {
	_, err := q.db.Exec(ctx, upsertUserSettings, arg.UserID, arg.Settings, arg.ServerUpdatedAt)
	return err
}
