// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: water_logs.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAllWaterLogs = `-- name: GetAllWaterLogs :many
SELECT id, amount_ml, logged_at, is_deleted, server_updated_at
FROM water_logs
WHERE user_id = $1
`

type GetAllWaterLogsRow struct {
	ID              uuid.UUID
	AmountMl        int32
	LoggedAt        pgtype.Timestamptz
	IsDeleted       bool
	ServerUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetAllWaterLogs(ctx context.Context, userID uuid.UUID) ([]GetAllWaterLogsRow, error) {
	rows, err := q.db.Query(ctx, getAllWaterLogs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllWaterLogsRow
	for rows.Next() {
		var i GetAllWaterLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountMl,
			&i.LoggedAt,
			&i.IsDeleted,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeltaWaterLogs = `-- name: GetDeltaWaterLogs :many
SELECT id, amount_ml, logged_at, is_deleted, server_updated_at 
FROM water_logs 
WHERE user_id = $1 AND server_updated_at > $2
`

type GetDeltaWaterLogsParams struct {
	UserID          uuid.UUID
	ServerUpdatedAt pgtype.Timestamptz
}

type GetDeltaWaterLogsRow struct {
	ID              uuid.UUID
	AmountMl        int32
	LoggedAt        pgtype.Timestamptz
	IsDeleted       bool
	ServerUpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetDeltaWaterLogs(ctx context.Context, arg GetDeltaWaterLogsParams) ([]GetDeltaWaterLogsRow, error) {
	rows, err := q.db.Query(ctx, getDeltaWaterLogs, arg.UserID, arg.ServerUpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDeltaWaterLogsRow
	for rows.Next() {
		var i GetDeltaWaterLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountMl,
			&i.LoggedAt,
			&i.IsDeleted,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWaterLogsInRange = `-- name: GetWaterLogsInRange :many
SELECT id, amount_ml, logged_at, is_deleted, server_updated_at
FROM water_logs
WHERE user_id = $1
  AND is_deleted = FALSE
  AND logged_at >= $2
  AND logged_at < $3
ORDER BY logged_at DESC
`

type GetWaterLogsInRangeParams struct {
	UserID     uuid.UUID
	LoggedAt   pgtype.Timestamptz
	LoggedAt_2 pgtype.Timestamptz
}

type GetWaterLogsInRangeRow struct {
	ID              uuid.UUID
	AmountMl        int32
	LoggedAt        pgtype.Timestamptz
	IsDeleted       bool
	ServerUpdatedAt pgtype.Timestamptz
}

// Returns a user's non-deleted logs whose logged_at falls within the half-open range [from, to). The client passes the start of the selected local day and the start of the following day, so day boundaries honour the client's timezone.
func (q *Queries) GetWaterLogsInRange(ctx context.Context, arg GetWaterLogsInRangeParams) ([]GetWaterLogsInRangeRow, error) {
	rows, err := q.db.Query(ctx, getWaterLogsInRange, arg.UserID, arg.LoggedAt, arg.LoggedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWaterLogsInRangeRow
	for rows.Next() {
		var i GetWaterLogsInRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.AmountMl,
			&i.LoggedAt,
			&i.IsDeleted,
			&i.ServerUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertWaterLog = `-- name: UpsertWaterLog :exec
INSERT INTO water_logs (id, user_id, amount_ml, logged_at, is_deleted, server_updated_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (id) DO UPDATE SET
    amount_ml = EXCLUDED.amount_ml,
    is_deleted = EXCLUDED.is_deleted,
    logged_at = EXCLUDED.logged_at,
    server_updated_at = EXCLUDED.server_updated_at
`

type UpsertWaterLogParams struct {
	ID              uuid.UUID
	UserID          uuid.UUID
	AmountMl        int32
	LoggedAt        pgtype.Timestamptz
	IsDeleted       bool
	ServerUpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertWaterLog(ctx context.Context, arg UpsertWaterLogParams) error {
	_, err := q.db.Exec(ctx, upsertWaterLog,
		arg.ID,
		arg.UserID,
		arg.AmountMl,
		arg.LoggedAt,
		arg.IsDeleted,
		arg.ServerUpdatedAt,
	)
	return err
}
