// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package models

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// WaterLog A single record of water consumed.
type WaterLog struct {
	// AmountMl Amount of water consumed in milliliters.
	AmountMl int `json:"amount_ml"`

	// Id Unique ID generated by the local device (Web/Desktop/Mobile).
	Id openapi_types.UUID `json:"id"`

	// IsDeleted Used for local-first sync. If true, the server tells other devices to delete this log.
	IsDeleted *bool `json:"is_deleted,omitempty"`

	// LoggedAt When the user drank the water (ISO 8601).
	LoggedAt time.Time `json:"logged_at"`
}
