// Package models provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package models

import (
	"fmt"
	"net/http"
	"time"

	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerWaterLog defines model for ServerWaterLog.
type ServerWaterLog struct {
	// AmountMl Amount of water consumed in milliliters.
	AmountMl int `json:"amount_ml"`

	// Id Unique ID generated by the local device (Web/Desktop/Mobile).
	Id openapi_types.UUID `json:"id"`

	// IsDeleted Used for local-first sync. If true, the server tells other devices to delete this log.
	IsDeleted bool `json:"is_deleted"`

	// LoggedAt When the user drank the water (ISO 8601).
	LoggedAt        time.Time `json:"logged_at"`
	ServerUpdatedAt time.Time `json:"server_updated_at"`
}

// WaterLog A single record of water consumed generated by a client.
type WaterLog struct {
	// AmountMl Amount of water consumed in milliliters.
	AmountMl int `json:"amount_ml"`

	// Id Unique ID generated by the local device (Web/Desktop/Mobile).
	Id openapi_types.UUID `json:"id"`

	// IsDeleted Used for local-first sync. If true, the server tells other devices to delete this log.
	IsDeleted bool `json:"is_deleted"`

	// LoggedAt When the user drank the water (ISO 8601).
	LoggedAt time.Time `json:"logged_at"`
}

// PostSyncJSONBody defines parameters for PostSync.
type PostSyncJSONBody = []WaterLog

// PostSyncParams defines parameters for PostSync.
type PostSyncParams struct {
	// Since The server_updated_at timestamp from the client's last successful sync.
	Since *time.Time `form:"since,omitempty" json:"since,omitempty"`
}

// PostSyncJSONRequestBody defines body for PostSync for application/json ContentType.
type PostSyncJSONRequestBody = PostSyncJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Sync local water logs with the server
	// (POST /sync)
	PostSync(ctx echo.Context, params PostSyncParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostSync converts echo context to params.
func (w *ServerInterfaceWrapper) PostSync(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params PostSyncParams
	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "since", ctx.QueryParams(), &params.Since, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter since: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostSync(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(options.BaseURL+"/sync", wrapper.PostSync, options.OperationMiddlewares["PostSync"]...)

}
